name: metering-data-backend
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "3002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    platform: linux/arm64
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "3003:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    platform: linux/arm64
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:5173"

volumes:
  postgres_data:
  redis_data: