name: metering-data-assessment

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    platform: linux/arm64
    networks:
      - backend-network

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    platform: linux/arm64
    ports:
      - "6379:6379"
    networks:
      - backend-network

  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - frontend-network
    depends_on:
      - backend-spring

  backend-spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"

      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - postgres
      - redis

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: